app = 'premiere-ecoute'
primary_region = 'cdg'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'premiere-ecoute.fr'
  PORT = '4000'

[http_service]
  internal_port = 4000
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ['app']
  
  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[metrics]
  port = 4000
  path = "/metrics"