# fly.toml app configuration file generated for premiere-ecoute on 2025-07-05T20:36:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'premiere-ecoute'
primary_region = 'cdg'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'premiere-ecoute.fr'
  PORT = '4000'

[http_service]
  internal_port = 4000
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ['app']
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"

[metrics]
  port = 4000
  path = "/metrics"