import { Handle, Position } from '@xyflow/react'
import { useState } from 'react'

const CARD_TYPE_LABELS = {
  intro: 'About',
  discography: 'Discography',
  members: 'Members',
  history: 'History',
}

/**
 * ArtistNode (also used for album nodes)
 *
 * Renders a stack of semantic cards for an entity.
 *
 * Navigation: clicks on elements with [data-entity-id] bubble up as a native
 * CustomEvent('explorer:open_node') — this covers both <mark> annotation hotspots
 * in prose text AND .explorer-album-row divs in DB-generated discography cards.
 *
 * Keep: the header Keep button dispatches 'explorer:keep' which the hook forwards
 * to the server as pushEvent("keeps:add", ...).
 *
 * data prop shape: { id, entity_type, entity_id, label, subtitle, thumbnail_url, cards[] }
 */
export function ArtistNode({ id, data }) {
  const [activeCard, setActiveCard] = useState(0)
  const cards = data.cards || []

  // Event delegation: handle clicks on any element with data-entity-id.
  // Covers <mark class="explorer-hotspot"> in prose AND .explorer-album-row divs.
  function handleCardClick(e) {
    const target = e.target.closest('[data-entity-id]')
    if (!target) return

    const entityId = target.dataset.entityId
    const entityType = target.dataset.entityType

    if (entityId && entityType) {
      // AIDEV-NOTE: use a native DOM event so the hook (outside React) can catch it.
      target.dispatchEvent(
        new CustomEvent('explorer:open_node', {
          bubbles: true,
          detail: { entityType, entityId, parentId: id },
        })
      )
    }
  }

  function handleKeep() {
    if (!data.entity_id) return
    const el = document.getElementById(`explore-canvas`)
    if (!el) return
    el.dispatchEvent(
      new CustomEvent('explorer:keep', {
        bubbles: false,
        detail: {
          entity_type: data.entity_type,
          entity_id: String(data.entity_id),
          label: data.label,
        },
      })
    )
  }

  const card = cards[activeCard]

  return (
    <div
      style={{ width: 440 }}
      className="bg-gray-800 border border-gray-700 rounded-xl shadow-2xl overflow-hidden flex flex-col"
    >
      {/* Node header */}
      <div className="flex items-start gap-3 p-4 border-b border-gray-700 bg-gray-900">
        {data.thumbnail_url && (
          <img
            src={data.thumbnail_url}
            alt={data.label}
            className="w-12 h-12 rounded-lg object-cover flex-shrink-0"
          />
        )}
        <div className="min-w-0 flex-1">
          <h3 className="font-semibold text-white truncate">{data.label}</h3>
          {data.subtitle && (
            <p className="text-xs text-gray-400 mt-0.5 truncate">{data.subtitle}</p>
          )}
        </div>
        {/* Keep button — only for DB-backed entities */}
        {data.entity_id && (
          <button
            onClick={handleKeep}
            title="Add to Keeps"
            className="flex-shrink-0 p-1.5 text-gray-500 hover:text-purple-400 transition-colors rounded-md hover:bg-gray-800"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
            </svg>
          </button>
        )}
      </div>

      {/* Card tab strip */}
      {cards.length > 1 && (
        <div className="flex border-b border-gray-700 overflow-x-auto">
          {cards.map((c, i) => (
            <button
              key={c.id}
              onClick={() => setActiveCard(i)}
              className={`px-3 py-2 text-xs font-medium whitespace-nowrap transition-colors ${
                i === activeCard
                  ? 'text-purple-400 border-b-2 border-purple-500'
                  : 'text-gray-500 hover:text-gray-300'
              }`}
            >
              {CARD_TYPE_LABELS[c.type] || c.title}
            </button>
          ))}
        </div>
      )}

      {/* Active card content */}
      {card && (
        // eslint-disable-next-line jsx-a11y/click-events-have-key-events
        <div
          className="p-4 overflow-y-auto text-sm text-gray-300 leading-relaxed explorer-card-content"
          style={{ maxHeight: 420 }}
          onClick={handleCardClick}
          // AIDEV-NOTE: dangerouslySetInnerHTML — content from Wikipedia (server-sanitized)
          // or from DB data (generated by fetch_node.ex). Not user-generated.
          dangerouslySetInnerHTML={{ __html: card.content_html }}
        />
      )}

      {/* React Flow connection handles */}
      <Handle type="target" position={Position.Left} className="!bg-purple-500" />
      <Handle type="source" position={Position.Right} className="!bg-purple-500" />
    </div>
  )
}
