/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active collection session
         * @description Returns the authenticated streamer's current active collection session.
         */
        get: operations["PremiereEcouteWeb.Api.Collection.DashboardController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete collection session
         * @description Completes the collection session and syncs kept tracks to the destination playlist.
         */
        post: operations["PremiereEcouteWeb.Api.Collection.DashboardController.complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide current track
         * @description Records the streamer's decision (kept/rejected/skipped) for the current track.
         */
        post: operations["PremiereEcouteWeb.Api.Collection.DashboardController.decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start collection session
         * @description Starts the authenticated streamer's pending collection session.
         */
        post: operations["PremiereEcouteWeb.Api.Collection.DashboardController.start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit collection vote
         * @description Submits a binary choice (1 or 2) for the active vote window. Streamers vote on their own session; viewers must supply a `username` body param (the broadcaster's username).
         */
        post: operations["PremiereEcouteWeb.Api.Collection.VoteController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/vote/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close vote window
         * @description Closes the active vote window in the current collection session.
         */
        post: operations["PremiereEcouteWeb.Api.Collection.DashboardController.close_vote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/vote/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open vote window
         * @description Opens a vote window for the current track(s) in the active collection session.
         */
        post: operations["PremiereEcouteWeb.Api.Collection.DashboardController.open_vote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current session
         * @description Returns the authenticated user's current active session state.
         */
        get: operations["PremiereEcouteWeb.Api.Session.DashboardController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Next track
         * @description Skips to the next track in the authenticated user's current session.
         */
        post: operations["PremiereEcouteWeb.Api.Session.DashboardController.next"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/previous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previous track
         * @description Skips to the previous track in the authenticated user's current session.
         */
        post: operations["PremiereEcouteWeb.Api.Session.DashboardController.previous"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start session
         * @description Starts the authenticated user's current session and advances to the first track.
         */
        post: operations["PremiereEcouteWeb.Api.Session.DashboardController.start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop session
         * @description Stops the authenticated user's current session.
         */
        post: operations["PremiereEcouteWeb.Api.Session.DashboardController.stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vote on current track
         * @description Submits a rating (0–10) for the current track in the session. Streamers vote on their own session directly; viewers must supply a `username` body param (the broadcaster's username).
         */
        post: operations["PremiereEcouteWeb.Api.Session.VoteController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile
         * @description Returns the authenticated user's profile settings.
         */
        get: operations["PremiereEcouteWeb.Api.User.ProfileController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update profile
         * @description Partially updates the authenticated user's profile settings. Only fields present in the request body are changed.
         */
        patch: operations["PremiereEcouteWeb.Api.User.ProfileController.update"];
        trace?: never;
    };
    "/api/user/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API status
         * @description Smoke-test route that confirms authentication is working and returns basic information about the authenticated user.
         */
        get: operations["PremiereEcouteWeb.Api.User.StatusController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wantlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get wantlist
         * @description Returns the authenticated user's wantlist with all items.
         */
        get: operations["PremiereEcouteWeb.Api.Wantlist.WantlistController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wantlist/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove wantlist item
         * @description Removes an item from the authenticated user's wantlist.
         */
        delete: operations["PremiereEcouteWeb.Api.Wantlist.ItemController.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wantlist/tracks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save current track
         * @description Saves the track currently playing on the broadcaster's stream to the authenticated user's wantlist.
         */
        post: operations["PremiereEcouteWeb.Api.Wantlist.TrackController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CollectionSession */
        CollectionSession: {
            current_index?: number;
            id?: number;
            kept_count?: number;
            rejected_count?: number;
            skipped_count?: number;
            /** @enum {string} */
            status?: "pending" | "active" | "completed";
        };
        /** CollectionVoteRequest */
        CollectionVoteRequest: {
            /**
             * @description 1 for option A, 2 for option B
             * @enum {integer}
             */
            choice: 1 | 2;
            /** @description Broadcaster username (required for viewers) */
            username?: string;
        };
        /** CompleteRequest */
        CompleteRequest: {
            /**
             * @description Remove kept tracks from origin playlist
             * @default false
             */
            remove_kept: boolean;
            /**
             * @description Remove rejected tracks from origin playlist
             * @default false
             */
            remove_rejected: boolean;
        };
        /** DecideRequest */
        DecideRequest: {
            /** @enum {string} */
            decision: "kept" | "rejected" | "skipped";
        };
        /** ErrorResponse */
        ErrorResponse: {
            error?: string;
        };
        /** ListeningSession */
        ListeningSession: {
            /** Format: uri */
            cover_url?: string | null;
            id?: number;
            /** @enum {string} */
            source?: "album" | "playlist" | "track";
            /** @example started */
            status?: string;
            viewer_score?: number | null;
        };
        /** OkResponse */
        OkResponse: {
            /** @example true */
            ok?: boolean;
        };
        /** OpenVoteRequest */
        OpenVoteRequest: {
            /**
             * @description Vote duration in seconds
             * @default 60
             */
            duration: number;
            /** @enum {string} */
            mode: "viewer_vote" | "duel" | "streamer_choice";
        };
        /** Profile */
        Profile: {
            /** @enum {string} */
            color_scheme?: "light" | "dark" | "system";
            /** @enum {string} */
            language?: "en" | "fr" | "it";
            radio_settings?: {
                enabled?: boolean;
                retention_days?: number;
                /** @enum {string} */
                visibility?: "private" | "public";
            };
            /** @example Europe/Paris */
            timezone?: string;
            widget_settings?: {
                /** @example #5b21b6 */
                color_primary?: string;
                /** @example #be123c */
                color_secondary?: string;
            };
        };
        /**
         * ProviderIds
         * @description Provider IDs keyed by provider name (spotify, deezer, tidal)
         */
        ProviderIds: {
            [key: string]: string;
        };
        /** SessionVoteRequest */
        SessionVoteRequest: {
            rating: number;
            /** @description Broadcaster username (required for viewers) */
            username?: string;
        };
        /** SessionVoteResponse */
        SessionVoteResponse: {
            /** @example true */
            ok?: boolean;
            rating?: number;
        };
        /** StatusResponse */
        StatusResponse: {
            /** @example ok */
            status?: string;
            /** Format: date-time */
            timestamp?: string;
            user?: {
                id?: number;
                role?: string;
                username?: string;
            };
        };
        /** Wantlist */
        Wantlist: {
            items?: components["schemas"]["WantlistItem"][];
        };
        /** WantlistItem */
        WantlistItem: {
            artist?: string | null;
            name?: string;
            /**
             * ProviderIds
             * @description Provider IDs keyed by provider name (spotify, deezer, tidal)
             */
            provider_ids?: {
                [key: string]: string;
            };
            /** @enum {string} */
            type?: "album" | "track" | "artist";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "PremiereEcouteWeb.Api.Collection.DashboardController.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSession"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Collection.DashboardController.complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Completion options */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Collection.DashboardController.decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Decision payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed or invalid decision */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Collection.DashboardController.start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No pending session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Collection.VoteController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Vote payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionVoteRequest"];
            };
        };
        responses: {
            /** @description Vote accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Broadcaster not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid choice or missing username */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Collection.DashboardController.close_vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Collection.DashboardController.open_vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Vote window options */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenVoteRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Session.DashboardController.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListeningSession"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Session.DashboardController.next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Session.DashboardController.previous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Session.DashboardController.start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Session.DashboardController.stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.Session.VoteController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Vote payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionVoteRequest"];
            };
        };
        responses: {
            /** @description Vote accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionVoteResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Broadcaster not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid rating */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "PremiereEcouteWeb.Api.User.ProfileController.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "PremiereEcouteWeb.Api.User.ProfileController.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Profile fields to update */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation errors */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "PremiereEcouteWeb.Api.User.StatusController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "PremiereEcouteWeb.Api.Wantlist.WantlistController.show": {
        parameters: {
            query?: {
                /** @description Filter by item type */
                type?: "album" | "track" | "artist";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wantlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wantlist"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "PremiereEcouteWeb.Api.Wantlist.ItemController.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wantlist item ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Item not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "PremiereEcouteWeb.Api.Wantlist.TrackController.create": {
        parameters: {
            query: {
                /** @description Twitch user ID of the broadcaster */
                broadcaster_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Track saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing broadcaster_id parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Broadcaster not found or no track currently playing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Track could not be saved */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
