name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # AIDEV-NOTE: Setup and install dependencies - foundation for all subsequent jobs
  deps:
    name: Setup and Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.0-otp-28'
          otp-version: '28.1'

      - name: Restore dependencies cache
        uses: actions/cache@v4
        id: deps-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

  # AIDEV-NOTE: Quality checks - format, credo, dialyzer, compile warnings
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    needs: deps

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.0-otp-28'
          otp-version: '28.1'

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore PLT cache
        uses: actions/cache@v4
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-plt-

      - name: Create PLTs directory
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: mkdir -p priv/plts

      - name: Run quality checks
        run: mix quality

  # AIDEV-NOTE: Unit tests with Postgres for Ecto and EventStore
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: deps

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: premiere_ecoute_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      MIX_ENV: test
      # AIDEV-NOTE: Postgres configuration matches the service above
      POSTGRES_DATABASE: premiere_ecoute_test
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOSTNAME: localhost
      POSTGRES_ENCRYPTION_KEY: dGVzdF9lbmNyeXB0aW9uX2tleV8zMl9ieXRlc19sb25nIQ==
      # AIDEV-NOTE: Spotify and Twitch credentials are fake values (not used in unit tests)
      SPOTIFY_CLIENT_ID: fake_spotify_client_id
      SPOTIFY_CLIENT_SECRET: fake_spotify_client_secret
      SPOTIFY_REDIRECT_URI: http://localhost:4000/auth/spotify/callback
      TWITCH_CLIENT_ID: fake_twitch_client_id
      TWITCH_CLIENT_SECRET: fake_twitch_client_secret
      TWITCH_REDIRECT_URI: http://localhost:4000/auth/twitch/callback
      TWITCH_WEBHOOK_CALLBACK_URL: http://localhost:4000/webhooks/twitch
      # AIDEV-NOTE: Feature flags and other service credentials
      AUTH_USERNAME: admin
      AUTH_PASSWORD: test_password
      RESEND_API_KEY: fake_resend_api_key
      SENTRY_DSN: https://fake@sentry.io/123456

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.0-otp-28'
          otp-version: '28.1'

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Run tests
        run: mix test

  # AIDEV-NOTE: Documentation generation - only runs after quality and tests pass
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    needs: [quality, tests]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.0-otp-28'
          otp-version: '28.1'

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Generate ExDoc
        run: mix ci.docs

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}

    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v4
